name: review
on:
  push:
jobs:
  build-binary:
    name: Build binary
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Build
        run: make build-binary
  test:
    name: Test
    runs-on: ubuntu-18.04
    needs:
      - build-binary
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Check out code into go module directory
        uses: actions/checkout@v2
      - name: Test
        run: make test
  build-image:
    name: Build image
    runs-on: ubuntu-18.04
    needs:
      - build-binary
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Check out code into go module directory
        uses: actions/checkout@v2
      - name: Build binary
        run: make build-binary
      - name: Build image
        run: make build-image
