name: Docker

on: [push]

env:
  IMAGE_NAME: go-boilerplate

jobs:
  push:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check out code into go module directory
        uses: actions/checkout@v2

      - name: Build binary
        run: make build-binary

      - name: Build image
        run: make build-image

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: make push-image
