name: review
on:
  pull_request:
jobs:
  build-binary:
    name: Build binary
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Build
        run: make build-binary
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Check out code into go module directory
        uses: actions/checkout@v2
      - name: Test
        run: make test
  build-image:
    name: Build image
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Check out code into go module directory
        uses: actions/checkout@v2
      - name: Build binary
        run: make build-binary
      - name: Build image
        run: make build-image
  coverage:
    name: Coverage
    needs:
      - test
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Check out code into go module directory
        uses: actions/checkout@v2
      - name: Build coverage report
        run: make coverage-report
      - name: Publish coverage
        run: |
          COVERAGE=$( go tool cover -func=coverage.out | grep total | grep -Eo [0-9.]+% )
          curl \
            --fail --show-error \
            -X POST \
            -u ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}\
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }} \
            -d "{\"state\":\"success\",\"context\":\"coverage\",\"description\":\"${COVERAGE}\",\"target_url\":\"https://github.com/${{ github.repository }}/actions/runs/{{ github.run_id }}\"}"
