apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:13.1
          name: postgres
          env:
            - name: POSTGRES_DB
              value: go-boilerplate
            - name: POSTGRES_USER
              value: go-boilerplate
            - name: POSTGRES_PASSWORD
              value: go-boilerplate
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres
      volumes:
        - name: postgres
          persistentVolumeClaim:
            claimName: postgres
